export const ListaProductos = [
  {
    id: 1,
    title: "Cristales orgánicos con Antirreflejo",
    price: "$35.000",
    img: "./Productos_Img/Cristales AR.jpeg",
  },
  {
    id: 2,
    title: "Vulk",
    img: "./Productos_Img/Arm Acetato Vulk.jpeg",
    price: "$115.000",
  },
  {
    id: 3,
    title: "Clip On Runflex",
    img: "./Productos_Img/Arm Clip on Runflex.jpeg",
    price: "$95.000",
  },
  {
    id: 4,
    title: "Elizabeth Arden Jazmin",
    img: "./Productos_Img/Arm E. Arden Grilamid.jpeg",
    price: "$120.000",
  },
  {
    id: 5,
    title: "Clivion",
    img: "./Productos_Img/Arm Pasta Clivion.jpeg",
    price: "$59.000",
  },
  {
    id: 6,
    title: "Usual Flex Niño",
    img: "./Productos_Img/Arm Usual Flex Niño.jpeg",
    price: "$39.900",
  },
  {
    id: 7,
    title: "Cristales Blue Cut",
    img: "./Productos_Img/Cristales Blue Cut.jpeg",
    price: "$43.000",
  },
  {
    id: 8,
    title: "Deportivo espejado",
    img: "./Productos_Img/Sol Deportivo.jpeg",
    price: "$115.000",
  },
  {
    id: 9,
    title: "360 The Dude",
    img: "./Productos_Img/Arm 360 The Dude.jpeg",
    price: "$79.000",
  },
  {
    id: 10,
    title: "Paula Cahen D'avers Maia RX",
    img: "./Productos_Img/Paula Maia RX.jpeg",
    price: "$79.000",
  },
  {
    id: 11,
    title: "Mormaii Recife RX",
    img: "./Productos_Img/Mormaii Recife RX.jpeg",
    price: "$89.000",
  },
  {
    id: 12,
    title: "Clip on Runflex",
    img: "./Productos_Img/Runflex Clip on.jpeg",
    price: "$95.000",
  },
  {
    id: 14,
    title: "Eleve Acetato Multicolor",
    img: "./Productos_Img/Eleve acetato.jpeg",
    price: "$120.000",
  },
  {
    id: 15,
    title: "Paula Cahen D' anvers Melite",
    img: "./Productos_Img/Paula Melite.jpeg",
    price: "$120.000",
  },
  {
    id: 16,
    title: "Usual flex niña",
    img: "./Productos_Img/Usual flex niña.jpeg",
    price: "$39.900",
  },
  {
    id: 17,
    title: "Mariana Arias ",
    img: "./Productos_Img/Mariana Arias metal.jpeg",
    price: "$115.000",
  },
  {
    id: 18,
    title: "Cordon elástico deportivo",
    img: "./Productos_Img/Cordon deportivo.jpeg",
    price: "$1.900",
  },
  {
    id: 19,
    title: "Gravity",
    img: "./Productos_Img/Gravity Acetato.jpeg",
    price: "$120.000",
  },
  {
    id: 20,
    title: "Limpia cristales",
    img: "./Productos_Img/Limpia cristales.jpeg",
    price: "$1.900",
  },
  {
    id: 21,
    title: "Soflens 59",
    img: "./Productos_Img/Soflens59.jpeg",
    price: "$39.900",
  },
  {
    id: 22,
    title: "Biomedics 55",
    img: "./Productos_Img/Biomedics55.jpeg",
    price: "$95.000",
  },
  {
    id: 23,
    title: "Rusty Polarizado",
    img: "./Productos_Img/Rusty Polarizado.jpeg",
    price: "$99.900",
  },
  {
    id: 24,
    title: "Renu Fresh 120ml",
    img: "./Productos_Img/Renu fresh 120.jpeg",
    price: "$7.900",
  },
  {
    id: 25,
    title: "Boston Clean RGP",
    img: "./Productos_Img/Boston Clean Rgp.jpeg",
    price: "10.900",
  },
  {
    id: 26,
    title: "Cordon elástico niños",
    img: "./Productos_Img/Cordon elastico chicos.jpeg",
    price: "$1.900",
  },
  {
    id: 27,
    title: "Vulk metálico",
    img: "./Productos_Img/Vulk metal rosa.jpeg",
    price: "$110.000",
  },
  {
    id: 28,
    title: "Rusty Runet",
    img: "./Productos_Img/Sol Runet.jpeg",
    price: "$120.000",
  },
  {
    id: 29,
    title: "Arlyt Express 120ml",
    img: "./Productos_Img/Arlyt Express.jpeg",
    price: "$7.900",
  },
  {
    id: 30,
    title: "Rusty Aviador Polarizado",
    img: "./Productos_Img/Rusty aviador.jpeg",
    price: "$110.000",
  },
];
